[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/fish"

[font]
size = 12

[window]
padding = { x = 4, y = 4 }

[mouse]
hide_when_typing = false
