[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/fish"

[font]
size = 12

[window]
padding = { x = 4, y = 4 }

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Middle", action = "None" }
]

[colors.primary]
background = "#000000"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"
