# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |lv|
    lv.uri = "qemu:///system"
    lv.storage_pool_name = "vagrant"
    lv.cpu_mode = "host-passthrough"
    lv.cpus = 4
    lv.memory = 8192
    lv.nested = true
    lv.graphics_type = "none"
  end
end
