set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'catppuccin/nvim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'easymotion/vim-easymotion'
Plugin 'FooSoft/vim-argwrap'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-surround'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

call vundle#end()

set nocompatible
syntax on
filetype plugin indent on

set nomodeline
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set laststatus=2
set confirm
set visualbell
set t_vb=
set mouse=a
set cmdheight=2
set number
set notimeout ttimeout ttimeoutlen=200
set shiftwidth=4
set softtabstop=4
set expandtab
set cc=80
set number relativenumber
set nu rnu
set ff=unix
" set pastetoggle=<F2> " use <leader>p instead
" set list
" set listchars=nbsp:?

" Set leader to space
let mapleader = "\<Space>"

" Map system clipboard yanking and pasting
map <leader>y "+y
map <leader>p "+p

" Easymotion prefix
map <Leader> <Plug>(easymotion-prefix)

" File commands
map <leader>j :e #<CR>
map <leader><leader> <C-p>

" Run norm command
map <C-n> :norm<Space>

" Faster navigation
map J }
map K {
map H b
map L w

" Set sensible navigation repeat directions
noremap , ;
noremap ; ,

" Splitting arguments
nnoremap gs :ArgWrap<CR>

" Highlighting
nnoremap <C-L> :noh<CR><C-L>
nnoremap <silent> <F5> :let _s=@/ <Bar> :%s/\s\+$//e <Bar> :let @/=_s <Bar> :nohl <Bar> :unlet _s <CR>

" Alt window navigation
nmap <silent> <A-h> :wincmd h<CR>
nmap <silent> <A-j> :wincmd j<CR>
nmap <silent> <A-k> :wincmd k<CR>
nmap <silent> <A-l> :wincmd l<CR>

nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

nmap <silent> <S-Up> :wincmd K<CR>
nmap <silent> <S-Down> :wincmd J<CR>
nmap <silent> <S-Left> :wincmd H<CR>
nmap <silent> <S-Right> :wincmd L<CR>

" Theme
colorscheme catppuccin-mocha
let g:airline_theme='minimalist'

" ctlrp setup
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'a'
