set nocompatible
syntax on
filetype plugin indent on

set nomodeline
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set laststatus=2
set confirm
set visualbell
set t_vb=
set mouse=a
set cmdheight=1
set number
set notimeout ttimeout ttimeoutlen=10
set shiftwidth=4
set softtabstop=4
set expandtab
set cc=80
set number relativenumber
set nu rnu
set ff=unix

" Set leader to space
let mapleader = "\<Space>"

" Map yanking, pasting and deleting to system clipboard
map <leader>y "+y
map <leader>p "+p
map <leader>d "+d

" File commands
map <leader>q :q<CR>
map <leader>w :wincmd w<CR>
map <leader>x :x<CR>
map <leader>j :e #<CR>

" xxd
nmap <leader>e :%!xxd<CR>
nmap <leader>r :%!xxd -r<CR>
vmap <leader>e !xxd<CR>
vmap <leader>r !xxd -r<CR>

" Run norm command
map <C-n> :norm<Space>

" Repeat last macro && ex command
map <leader>. @@
map <leader>, @:

" Faster navigation
map J }
map K {
map H b
map L w

" Set sensible navigation repeat directions
noremap , ;
noremap ; ,

" Highlighting
nnoremap <C-L> :noh<CR><C-L>
nnoremap <silent> <F5> :let _s=@/ <Bar> :%s/\s\+$//e <Bar> :let @/=_s <Bar> :nohl <Bar> :unlet _s <CR>
