# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/testing64"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |lv|
    lv.uri = "qemu:///system"
    lv.storage_pool_name = "vagrant"
    lv.cpu_mode = "host-passthrough"
    lv.cpus = 4
    lv.memory = 8192
    lv.nested = true
    # Debian installation hangs w/ graphics disabled currently for some reason.
    # As a workaround, do not disable graphics during the initial `$ vagrant
    # up`. After the machine is installed, shut it down and disable graphics
    # w/: `$ virsh edit <domain>` `/graphics<CR>d2j:x<CR>`. Verify this on the
    # hypervisor w/ `$ ss -an | grep 5700`.
    # lv.graphics_type = "none"
  end
end
