---

- hosts: all
  tasks:

    - name: Update all packages
      become: yes
      dnf:
        name: "*"
        state: latest

    - name: Install build dependencies
      become: yes
      dnf:
        name:
          - git
          - make
        state: latest

    - name: Create github directory
      file:
        path: /home/vagrant/github
        state: directory
        mode: 0755

    - name: Clone dotfiles
      git:
        repo: "https://github.com/jukuisma/dotfiles.git"
        dest: /home/vagrant/github/dotfiles

    - name: Install Fedora specific dependencies
      make:
        chdir: /home/vagrant/github/dotfiles
        target: fedora

    - name: Configure all software
      make:
        chdir: /home/vagrant/github/dotfiles
