# Oh My Zsh setup
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="gnzh"
plugins=(
    vi-mode
    fzf
    rust
    zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh

# Env variables
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR='nvim'
export KEEPASSXC_DB=''
export KEEPASSXC_KEY=''
export LIBVIRT_DEFAULT_URI='qemu:///system'
export VAGRANT_DEFAULT_PROVIDER='libvirt'
export XM5_UUID=''

# Zsh key bindings
bindkey -s '^F' 'ts^M'
bindkey '^Y' autosuggest-accept
bindkey '^@' autosuggest-accept

# Aliases
alias ccat="batcat"
alias c="clear"
alias clipnt="wl-copy -c"
alias connect-xm5="bluetoothctl connect $XM5_UUID"
alias disconnect-xm5="bluetoothctl disconnect $XM5_UUID"
alias rtop="radeontop -c"

alias t="tmux"
alias ta="tmux a"
alias tl="tmux ls"
alias ts="tmux-sessionizer"
alias tks="tmux kill-server"

alias vim="nvim"
alias vi="nvim"
alias v="nvim"
alias vim!="/usr/bin/vim"
alias vi!="/usr/bin/vim"
alias v!="/usr/bin/vim"
alias vimb="vim -b"
alias vimd="vim -d"

alias j="sudo journalctl"
alias s="sudo systemctl"

alias ga="git add"
alias gb="git blame"
alias gc="git commit"
alias gco="git checkout"
alias gd="git diff"
alias gl="git log"
alias gm="git merge"
alias gp="git pull"
alias gpu="git push"
alias grb="git rebase"
alias grs="git reset"
alias gs="git status"
alias gsh="git show"

function vault () {
    entry="$1"
    keepassxc-cli clip -k $KEEPASSXC_KEY $KEEPASSXC_DB $entry 0
}

function rand () {
    tr -dc A-Za-z0-9 </dev/urandom | head -c $1
    echo
}

function replace () {
    if [ "$#" -ne 2 ]; then
        echo "Must be 2 parameters: e.g. 'replace replace_this with_this'"
        return 1
    fi

    limit=50  # if more than 50 grep results found, do nothing
    search="$1"
    replace="$2"
    length=$(grep -rlI --color=never "$search" | wc -l)

    if [ "$length" -ne 0 ] && [ "$length" -lt $limit ]; then
        for file in $(grep -rlI --color=never "$search")
        do
            nvim -c "%s/$search/$replace/gc" -c 'wq' "$file"
        done
    else
        echo "$length results found, nothing done"
    fi
}

function git-far () {
    pattern="$1"
    if [ -z "$pattern" ]; then
        echo "Usage:"
        echo "git-far 's/foo/bar/g'"
        return
    fi

    # Check if git working tree is clean
    if [ ! -z "$(git status --porcelain)" ]; then
        echo "Working directory unclean!"
        return
    fi

    sed --follow-symlinks -i "$pattern" $(git ls-files)

    # Stash changes so user can preview them before applying them
    git stash --include-untracked
    git stash show -p

    read -q "REPLY?Apply changes? [y/n] " -n 1 -r
    echo
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        git stash pop
        return
    fi

    git stash drop
}

function plugins () {
    git clone --depth=1 \
        https://github.com/VundleVim/Vundle.vim.git \
        ~/.vim/bundle/Vundle.vim
    git clone --depth=1 \
        https://github.com/ohmyzsh/ohmyzsh.git \
        ~/.oh-my-zsh
    git clone --depth=1 \
        https://github.com/zsh-users/zsh-autosuggestions \
        ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
}

function virt-install-debian () {
    domain="$1"
    virt-install \
        --name $domain \
        --ram 8192 --vcpus 4 \
        --disk pool=virt,size=20 \
        --os-variant debian12 \
        --graphics none \
        --console pty,target_type=serial \
        --location 'https://ftp.debian.org/debian/dists/bookworm/main/installer-amd64/' \
        --extra-args 'console=ttyS0,115200n8 serial'
}

function toggle-gitconfig () {
    selected=$(ls ~/.gitconfig_* | fzf)
    cp "$selected" ~/.gitconfig
}

function trprompt () {
    export PROMPT=$(echo $PROMPT | sed 's/ $(git_prompt_info)//')
}

function activate () {
    source venv/bin/activate
    export PROMPT=$(echo $PROMPT | sed 's/(venv) ╭─/╭─(venv) /')
}

function syscalls () {
    grep -E '^[0-9]' ~/kernel/linux-*/arch/x86/entry/syscalls/syscall_64.tbl |\
        fzf |\
        cut -d $'\t' -f 1 |\
        wl-copy -n
}

function sshfs-vagrant () {
    host="$1"
    sshfs -o idmap=user $host:/home/vagrant/scratch ~/scratch
}

function r2d2 () {
    file="$1"
    r2 -nqc 'px $s' $file | less
}
