---

- hosts: all
  tasks:

    - name: Install build dependencies
      dnf:
        name:
          - git
          - make
        state: latest
      become: yes

    - name: Create github directory
      file:
        path: /home/vagrant/github
        state: directory
        mode: 0755

    - name: Clone dotfiles
      git:
        repo: "https://github.com/jukuisma/dotfiles.git"
        dest: /home/vagrant/github/dotfiles

    - name: Install RHEL specific dependencies
      make:
        chdir: /home/vagrant/github/dotfiles
        target: rhel

    - name: Configure all software
      make:
        chdir: /home/vagrant/github/dotfiles
