# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/39-cloud-base"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |lv|
    lv.cpus = 4
    lv.memory = 8192
    lv.nested = true
  end
end
